name: Image CI

on:
  pull_request:
    branches:
    - develop
    - main

env:
  JKTP_IMAGE_FILES_URL: https://files.jacktrip.org/binaries/jacktrip-image-files-20220630.tar.gz

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v2
    - name: Checkout jacktrip-agent
      uses: actions/checkout@v3
      with:
        repository: jacktrip/jacktrip-agent
        ref: develop
        path: jacktrip-agent
    - name: Build jacktrip-agent
      run: |
        cd ${GITHUB_WORKSPACE}/jacktrip-agent
        make agent-arm
      env:
        DOCKER_BUILDKIT: 1
    - name: Checkout pi-gen
      uses: actions/checkout@v3
      with:
        repository: RPi-Distro/pi-gen
        ref: buster
        path: pi-gen
    - name: Checkout jacktrip-image
      uses: actions/checkout@v3
      with:
        path: pi-gen/jacktrip-image
    - name: Fetch binaries
      run: |
        cd ${GITHUB_WORKSPACE}/pi-gen
        wget -q -O - ${JKTP_IMAGE_FILES_URL} | tar -C jacktrip-image/00-sys-tweaks/files -xzvf -
        cp ${GITHUB_WORKSPACE}/jacktrip-agent/jacktrip-agent-arm jacktrip-image/00-sys-tweaks/files/jacktrip-agent
    - name: Patch files
      run: |
        cd ${GITHUB_WORKSPACE}/pi-gen
        cp jacktrip-image/config .
        patch -p1 < jacktrip-image/pi-gen.patch
    - name: Build image
      run: |
        cd ${GITHUB_WORKSPACE}/pi-gen
        sudo ./build-docker.sh
        export VERSION=`date +"%Y%m%d"`
        cd deploy
        sudo mv *.zip jacktrip-rpi-${VERSION}.zip
        sudo sha256sum jacktrip-rpi-${VERSION}.zip | sudo tee -a jacktrip-rpi-${VERSION}.zip.sha256
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jacktrip-rpi-image
        path: pi-gen/deploy/jacktrip-rpi-*
        retention-days: 1
